### ISSUE TITLE
Search by pokemon name

### ISSUE THREAD

**Issue by ami** [pokedextracker/pokedextracker.com#18]
- search bar
- client-side filtering of query by prefix and/or substring matching
- new, nonbox view
- extensible for when we eventually support [multiple languages](https://github.com/pokedextracker/pokedextracker.com/issues/146)

**Comment by robinjoseph08** [comment]
something to keep in mind: https://angular.io/docs/ts/latest/guide/pipes.html#!#no-filter-pipe

angular 2 removed the default `filter` pipe that would've made the filtering easy (much like in the example at the bottom of [this page](https://docs.angularjs.org/api/ng/filter/filter)) due to performance reasons

**Comment by ami** [comment]
boooooo

**Comment by GiacomoLaw** [comment]
Would be awesome if I could search to find a mon!
