### ISSUE TITLE
Allow Pokedexes to include both generations

### ISSUE THREAD

**Issue by AussieEevee** [pokedextracker/pokedextracker.com#262]
Currently the Pokedex options lets you select from Gen 6 or 7... I'd like for it to allow me to select "Both" so I can select a Pokemon and see their locations for all 6 games that PokeBank connects to.

**Comment by robinjoseph08** [comment]
Thanks for the request! We've gotten this request a few times before, so it's definitely something on our todo list.

Instead of having a "Both", we'd probably just show the gen 6 locations whenever a gen 7 National Dex is viewed. There's probably very few reasons why you wouldn't want to see those locations too.

**Comment by robinjoseph08** [comment]
We actually have this already at #249 so I'll go ahead and close this to keep everything in one place!
