### ISSUE TITLE
Meltan/Melmetal in Generation 7 National Pokedex

### ISSUE THREAD

**Issue by atumang** [pokedextracker/pokedextracker.com#320]
From what I understand, USUM has the most up to date National Dex, and Let's Go does not have a National Dex. However, technically [Meltan and Melmetal are Gen 7 Pokemon](https://bulbapedia.bulbagarden.net/wiki/Meltan_(Pok%C3%A9mon)) so I thought it would be nice to include them in a Gen 7 National Dex page somehow for a complete Living Dex.
I guess the options would be:

1. Add them to the USUM National Dex (even though they're not obtainable through USUM)
2. Add a National regionality option to Let's Go (even though the games don't have a national dex)

**Comment by ami** [comment]
hey @atumang! we built this tracker for the purposes of tracking an obtainable living dex in each generation. therefore, while meltan and melmetal are "technically" gen 7 pokemon, since they are unobtainable in the gen 7 games, we won't be adding them.

however, if the day comes where they are obtainable, we certainly will add them! additionally, once LGPE has pokebank and an official national dex, we will also add that as well.

hope this makes sense!
