### ISSUE TITLE
Pokèbank expiration countdown?

### ISSUE THREAD

**Issue by ian4uh** [pokedextracker/pokedextracker.com#321]
Pokèbank is vital to many people completing and storing their living Dex. I often worry I'm going to miss the deadline to renew it. 

I think a count down , or calculated date of when you have to buy another year of pokèbank could be helpful.

I see it only being viewable to a logged in user near the 3ds and switch codes on their main user profile.

**Comment by iArcadia** [comment]
Even if you licence expires, pokemons which are on Pokebank servers are not deleted. I waited one and a half year before buying a new licence, and all my pokemons were where they were before.

**Comment by robinjoseph08** [comment]
Thanks for the suggestion @ian4uh!

As @iArcadia said, there really isn't a huge consequence of letting your Pokebank subscription expire since you can just log back in and renew to access all previous Pokemon. In addition, Pokebank technically isn't necessary to store your final Living Dex; your game's local PC actually has enough room to contain all of your Pokemon. So if you're really scared of losing Pokebank, you can opt to not use it for final storage. Because of these reasons, we're probably not going to implement this feature. Thanks for your input though! We appreciate it!
