### ISSUE TITLE
Custom dex

### ISSUE THREAD

**Issue by Dandriii** [pokedextracker/pokedextracker.com#322]
Hi

I see that many are requesting a dex for this game and a dex for that game, and a dex with all forms and so on. 
I dont know how easy or difficult it is to make a new standard dex, but I do believe that however many you make you won't make everyone happy.

My suggestion is add an option to make custom dexes so that everyone can make their own personal dex with whatever they want in it.
* Make every sprite available 
* Let us sort them ourself, do we want alolan forms for them self or do we want them on their dexnumber.
* Allow them to choose how many rows/column.  Today it is 5x6. If we can change it to 5x5 we can use it with Pokemon Go or 3x3 so that I can check my TCG evolutiondex.
* Sort/show only unmarked pokemon

Thanks for the work so far. It has been a huge help these last couple of games.

**Comment by ami** [comment]
thanks for the feedback @Dandriii! i believe your requests are encompassed by these other tickets, so i'll be closing this one. feel free to recomment if you think i've missed something!

- Make every sprite available - Not sure what you mean by this?
- Let us sort them ourself, do we want alolan forms for them self or do we want them on their dexnumber: #328
- Allow them to choose how many rows/column. Today it is 5x6. If we can change it to 5x5 we can use it with Pokemon Go or 3x3 so that I can check my TCG evolutiondex. #327
- Sort/show only unmarked pokemon #136
