### ISSUE TITLE
Improve search functionality (search by number, show family, jump to result)

### ISSUE THREAD

**Issue by ugster1** [pokedextracker/pokedextracker.com#336]
Hi, I love the tracker and use it for my game-overlapping living dex. I have several feature wishes, that would improve my experience immensely:

1. Searching for a number should also filter the right pokemon via its corresponding national dex number.
This would make it a whole lot easier for players in another language, since I don't have to google for the english pokemon name first.

2. For living dex it would be awesome if a search could also show the evolutions of the pokemon, making it easy to see if I can breed or evolve it.

3. In the same vein as #2 it would be awesome if the search for a specific name or number could scroll the page to its corresponding entry, instead of filtering it out.

**Comment by xAlien95** [comment]
For 3., what if after filtering with search, clicking on a tile doesn't toggle it but instead scrolls to the corresponding entry?

**Comment by ami** [comment]
Hey @ugster1, thanks for reaching out! 

1. This is a great feature request! We are already hoping to improve search/filtering in general so I've added this request to the existing issue: #325 

2. We actually don't want the search/filter functionality to do this because search/filtering doesn't usually function in that way. You can see the evolution line in the info panel. I think what you might be looking for more is #197 or #136 

3. You can accomplish this by using Ctrl + F in your browser.

I'll be closing this issue for now as I believe all the requests are encompassed elsewhere :)
