### ISSUE TITLE
Add Galarian Slowpoke to Pokemon Sword/Shield Pokedex

### ISSUE THREAD

**Issue by Chamberly** [pokedextracker/pokedextracker.com#348]
https://swordshield.pokemon.com/en-us/expansionpass/pokemon/slowpoke/

There will be new expansion pack coming soon with more as well. Right now it doesn't have a dex # so it just additional.

Ah here is more too.
https://swordshield.pokemon.com/en-us/expansionpass/pokemon/kubfu/
https://swordshield.pokemon.com/en-us/expansionpass/pokemon/urshifu/
https://swordshield.pokemon.com/en-us/expansionpass/pokemon/gigantamax-urshifu/
https://swordshield.pokemon.com/en-us/expansionpass/pokemon/calyrex/

**Comment by ami** [comment]
thanks @Chamberly!

we actually won't be adding galarian slowpoke to the regional swsh dex just yet because it doesn't have a galarian dex number, even tho he is catchable. unfortunately in our system, without a galarian dex number, the system won't work very well. kubfu, urshifu, and all other pokemon who will become available with the expansion passes will be added all at once when those are released (https://github.com/pokedextracker/pokedextracker.com/issues/350)

we will however be including galarian slowpoke in the national dex update (https://github.com/pokedextracker/pokedextracker.com/issues/349)
