### ISSUE TITLE
Add support for Pokemon Go

### ISSUE THREAD

**Issue by donaldelrod** [pokedextracker/pokedextracker.com#372]
It would be nice to add support for Pokemon Go, I know it would be pretty broken at first as all the pokemon would have location data that wouldn't work for the game, but I think just creating the list for now would be a great feature, especially with Pokemon Go soon being added to Pokemon HOME. I might work on this myself if I get some free time

**Comment by ami** [comment]
sorry @donaldelrod, we don't plan to support Pokemon Go in this platform any time soon, as neither of us play so we're not informed enough to know how to best support it!

**Comment by Azekthi** [comment]
Where are the data entries located for where/how to catch a Pokemon? If those are on GitHub, we could help out by contributing Go information.

Just some musings: Like how the SwSh DLCs are handled by separate sections, Go can be handled by having each region as its own section, since its Dex is separated by originating region (except Meltan and Melmetal, which are listed in their own "Unknown" region). Alolan and Galarian forms could be included as well, but not Gigantamax.
