### ISSUE TITLE
Changing password for main website?

### ISSUE THREAD

**Issue by DoobliheimGH** [pokedextracker/pokedextracker.com#395]
Am I missing something, or is there no way to change the password for your account? I'm not even seeing a "Forgot Password" button that's available to use.

**Comment by ami** [comment]
Hey @DoobliheimGH! When you are signed in, you can change your password by going to your Account Settings.

If you are not signed in and you have forgotten your password, unfortunately there is no way to do this from the main site. This is because we have no contact information saved per profile (e.g. an email address), so there's no place for us to send a password reset link.

If you have forgotten your password, feel free to [DM us on twitter](https://twitter.com/pokedextracker) or [send us an email](pokedextrackerapp@gmail.com) and we can chat privately and manually reset the password for you.
