### ISSUE TITLE
`yarn test` fails on api project with error `Cannot find module '../../src/models/box'`

### ISSUE THREAD

**Issue by jcreek** [pokedextracker/pokedextracker.com#452]
Exactly as stated above, `capture.test.js` in `test/models` requires a module that does not exist in the master branch's source code, making the tests throw.

To reproduce, just set up the project locally following the instructions in the readme, then try to run `yarn test`.

Expected behaviour is that there should be a module at the path the code is expecting.

**Comment by robinjoseph08** [comment]
Hey @jcreek, thanks for the question and sorry for the delay to answer. There was a period of time where the tests were just slowing development down (e.g. getting new games supported when they come out), so in an effort to go faster, I started ignoring the tests and stopped running them in CI. So that's why the API tests were in a state where they couldn't be run.

Recently, I rewrote it over in Golang, and I decided that I'll only test things that actually deserve tests instead of trying to just achieve 100% coverage, so moving forward, I shouldn't hit the scenario where I need to start ignoring the state of the tests.

Since this error is no longer happening, I'm going to close this issue.
